# Generated by Django 3.0.5 on 2021-06-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(default=0, unique=True)),
                ('full_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=15)),
                ('contact_number', models.IntegerField(default=0, max_length=10, unique=True)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
    ]
