# Generated by Django 3.0.5 on 2021-06-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210623_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
