# Generated by Django 3.0.5 on 2021-06-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210623_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
