# Generated by Django 3.0.5 on 2021-07-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210707_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contact_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
