# Generated by Django 3.0.5 on 2021-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210623_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='/image/Elon_Musk_Royal_Society_crop1_Fqs4Y5r.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
