# Generated by Django 3.2.2 on 2021-06-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventgallery_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='mainImage',
            field=models.BooleanField(default=False),
        ),
    ]
