# Generated by Django 3.2.2 on 2021-07-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210707_0803'),
        ('events', '0003_auto_20210708_1153'),
    ]

    operations = [
    ]
