# Generated by Django 3.2.2 on 2021-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210624_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='day',
        ),
        migrations.RemoveField(
            model_name='news',
            name='month',
        ),
        migrations.RemoveField(
            model_name='news',
            name='year',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
