# Generated by Django 3.2.2 on 2021-06-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pdf',
        ),
    ]
