# Generated by Django 3.2 on 2021-06-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_description', models.CharField(max_length=120)),
                ('contact_number_1', models.IntegerField()),
                ('contact_number_2', models.IntegerField()),
                ('email_id', models.EmailField(max_length=22)),
                ('address', models.CharField(max_length=8)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=40)),
                ('post', models.CharField(max_length=20)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('superAdmin', models.BooleanField(default=True)),
            ],
        ),
    ]
