# Generated by Django 3.0.5 on 2021-07-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images')),
                ('description', models.TextField(max_length=500)),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.IntegerField(default=0)),
                ('school_address', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
