# Generated by Django 3.0.5 on 2021-06-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutAndStaffs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Staffs',
        ),
    ]
