# Generated by Django 3.0.5 on 2021-07-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutAndStaffs', '0002_about_about_video'),
        ('aboutAndStaffs', '0002_alter_about_id'),
    ]

    operations = [
    ]
