# Generated by Django 3.0.5 on 2021-06-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutAndStaffs', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='school_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
