# Generated by Django 3.0.5 on 2021-06-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutAndStaffs', '0004_auto_20210607_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=100)),
                ('teacher', models.BooleanField(default=True)),
                ('principal', models.BooleanField(default=False)),
            ],
        ),
    ]
