# Generated by Django 3.0.5 on 2021-06-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutAndStaffs', '0005_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
