# Generated by Django 3.2.2 on 2021-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutAndStaffs', '0006_auto_20210607_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
