# Generated by Django 3.0.5 on 2021-06-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutAndStaffs', '0008_auto_20210617_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
