# Generated by Django 3.0.5 on 2021-06-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutAndStaffs', '0009_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(default='images/user.png', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
