# Generated by Django 3.0.5 on 2021-07-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fee_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('student_id', models.IntegerField(default=0)),
                ('full_name', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=1)),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('attendance', models.IntegerField(default=0)),
                ('user_created', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Students_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('strength', models.IntegerField(default=0)),
                ('tution_fees', models.IntegerField(default=0)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveSmallIntegerField()),
                ('obtained_marks', models.PositiveSmallIntegerField()),
                ('isPresent', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Students_Class')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Class_Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Students_Class'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('clear', models.BooleanField()),
                ('fine', models.FloatField()),
                ('fee_trans_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Fee_Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.PositiveSmallIntegerField(default=0)),
                ('total_marks', models.PositiveSmallIntegerField(default=0)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('createdBy', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
            ],
        ),
        migrations.AddField(
            model_name='fee_transaction',
            name='fee_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student.Fee_Type'),
        ),
        migrations.AddField(
            model_name='fee_transaction',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student'),
        ),
        migrations.AddField(
            model_name='class_subject',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Students_Class'),
        ),
    ]
