# Generated by Django 3.2.2 on 2021-06-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('fee_type', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('fine', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='class_subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='students_class',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Student_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.fees')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
            ],
        ),
        migrations.AddField(
            model_name='fees',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.students_class'),
        ),
        migrations.CreateModel(
            name='Fee_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('paid_date', models.DateField()),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.fees')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Advance_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('months', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
            ],
        ),
    ]
