# Generated by Django 3.2.2 on 2021-06-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210623_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('clear', models.BooleanField()),
                ('fine', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fees',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='student_fee',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='student_fee',
            name='student',
        ),
        migrations.RenameField(
            model_name='fee_transaction',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='fee_transaction',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='fee_transaction',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='fee_transaction',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fee_transaction',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fee_transaction',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Advance_Payment',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='Student_Fee',
        ),
        migrations.AddField(
            model_name='payments',
            name='fee_trans_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.fee_transaction'),
        ),
        migrations.AddField(
            model_name='fee_transaction',
            name='fee_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student.fee_type'),
        ),
    ]
