# Generated by Django 3.0.5 on 2021-06-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210623_1140'),
        ('student', '0002_auto_20210623_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveSmallIntegerField()),
                ('obtained_marks', models.PositiveSmallIntegerField()),
                ('isPresent', models.BooleanField()),
                ('createdAt', models.DateTimeField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Students_Class')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Class_Subject')),
                ('sutdent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
