# Generated by Django 3.2.2 on 2021-06-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210624_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.AddField(
            model_name='fee_type',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
