# Generated by Django 3.0.5 on 2021-07-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210707_1310'),
        ('student', '0003_auto_20210707_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalresult',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher'),
        ),
    ]
