# Generated by Django 3.0.5 on 2021-07-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210707_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student.Students_Class'),
            preserve_default=False,
        ),
    ]
