# Generated by Django 3.0.5 on 2021-06-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_finalresult_exam_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectresult',
            old_name='sutdent_id',
            new_name='student_id',
        ),
    ]
