# Generated by Django 3.0.5 on 2021-07-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210710_0542'),
        ('student', '0006_auto_20210711_1616'),
    ]

    operations = [
    ]
