# Generated by Django 3.0.5 on 2021-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210626_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='attendence',
            new_name='attendance',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
