# Generated by Django 3.0.5 on 2021-06-29 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_image'),
        ('student', '0008_auto_20210627_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_class',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher'),
        ),
    ]
