# Generated by Django 3.0.5 on 2021-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210711_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
