# Generated by Django 3.0.5 on 2021-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fee_trans_id',
        ),
        migrations.AddField(
            model_name='student',
            name='bus_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Fee_Transaction',
        ),
        migrations.DeleteModel(
            name='Fee_Type',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
