# Generated by Django 3.0.5 on 2021-07-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210630_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_created',
            field=models.IntegerField(default=0),
        ),
    ]
