# Generated by Django 3.0.5 on 2021-09-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210904_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_fees', models.IntegerField(default=0)),
                ('bus_fees', models.IntegerField(default=0)),
                ('total_fees', models.IntegerField(default=0)),
                ('session_month_name', models.CharField(max_length=25)),
                ('session_month', models.IntegerField(default=0)),
                ('session_year', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.CharField(max_length=20)),
                ('is_message_sent', models.IntegerField(default=0)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Students_Class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
            ],
        ),
    ]
