# Generated by Django 3.0.5 on 2021-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_fees',
            name='is_fined',
            field=models.BooleanField(default=False),
        ),
    ]
