# Generated by Django 3.0.5 on 2021-09-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_fees_is_fined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students_class',
            old_name='tution_fees',
            new_name='tuition_fees',
        ),
    ]
